DEBUG 2022-09-16 14:44:33.841 UTC: 	 CRAB Client version: v3.220823
DEBUG 2022-09-16 14:44:33.842 UTC: 	 Running on: Linux lxplus712.cern.ch 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-09-16 14:44:33.842 UTC: 	 Executing command: 'status'
DEBUG 2022-09-16 14:44:33.842 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adlintul/.crab3
DEBUG 2022-09-16 14:44:41.621 UTC: 	 CRAB Client version: v3.220823
DEBUG 2022-09-16 14:44:41.622 UTC: 	 Running on: Linux lxplus712.cern.ch 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-09-16 14:44:41.622 UTC: 	 Executing command: 'status'
DEBUG 2022-09-16 14:44:41.622 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adlintul/.crab3
DEBUG 2022-09-18 18:33:13.953 UTC: 	 CRAB Client version: v3.220823
DEBUG 2022-09-18 18:33:13.954 UTC: 	 Running on: Linux lxplus795.cern.ch 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-09-18 18:33:13.954 UTC: 	 Executing command: 'submit'
DEBUG 2022-09-18 18:33:13.954 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adlintul/.crab3
INFO 2022-09-18 18:33:13.955 UTC: 	 Will use CRAB configuration file qcd_nanoaod.py
DEBUG 2022-09-18 18:33:13.955 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-09-18 18:33:14.074 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-09-18 18:33:14.075 UTC: 	 Working area '/afs/cern.ch/work/a/adlintul/public/scouting/13p6/CMSSW_12_3_7/src/Run3ScoutingAnalysisTools/Analysis/run/crab_projects/crab_ScoutingPFQCDNanoAOD' already exists 
Please change the requestName in the config file
ERROR 2022-09-18 18:33:14.075 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/work/a/adlintul/public/scouting/13p6/CMSSW_12_3_7/src/Run3ScoutingAnalysisTools/Analysis/run/crab_projects/crab_ScoutingPFQCDNanoAOD' already exists 
Please change the requestName in the config file
INFO 2022-09-18 18:33:14.100 UTC: 	 Log file is /afs/cern.ch/work/a/adlintul/public/scouting/13p6/CMSSW_12_3_7/src/Run3ScoutingAnalysisTools/Analysis/run/crab.log
DEBUG 2022-09-19 15:36:38.734 UTC: 	 CRAB Client version: v3.220823
DEBUG 2022-09-19 15:36:38.735 UTC: 	 Running on: Linux lxplus785.cern.ch 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-09-19 15:36:38.735 UTC: 	 Executing command: 'submit'
DEBUG 2022-09-19 15:36:38.736 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adlintul/.crab3
INFO 2022-09-19 15:36:38.760 UTC: 	 Will use CRAB configuration file data.py
DEBUG 2022-09-19 15:36:38.760 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-09-19 15:36:38.835 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-09-19 15:36:38.850 UTC: 	 Working area '/afs/cern.ch/work/a/adlintul/public/scouting/13p6/CMSSW_12_3_7/src/Run3ScoutingAnalysisTools/Analysis/run/crab_projects/crab_ScoutingPFRun3_2nd' already exists 
Please change the requestName in the config file
ERROR 2022-09-19 15:36:38.850 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220823.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/work/a/adlintul/public/scouting/13p6/CMSSW_12_3_7/src/Run3ScoutingAnalysisTools/Analysis/run/crab_projects/crab_ScoutingPFRun3_2nd' already exists 
Please change the requestName in the config file
INFO 2022-09-19 15:36:38.881 UTC: 	 Log file is /afs/cern.ch/work/a/adlintul/public/scouting/13p6/CMSSW_12_3_7/src/Run3ScoutingAnalysisTools/Analysis/run/crab.log
